// PolicyManager.swift — OpenShell YAML policy generation, parsing, and template management

import Foundation

/// Manages OpenShell security policies: generation, templates, validation, and persistence.
public final class PolicyManager: Sendable {
    /// Directory where policies are stored
    public let policyDirectory: URL

    public init(policyDirectory: URL? = nil) {
        if let dir = policyDirectory {
            self.policyDirectory = dir
        } else {
            let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first!
            self.policyDirectory = appSupport.appendingPathComponent("mChatAI/Policies")
        }
        try? FileManager.default.createDirectory(at: self.policyDirectory, withIntermediateDirectories: true)
    }

    // MARK: - Policy Model

    /// A structured OpenShell policy
    public struct Policy: Sendable {
        public var name: String
        public var version: Int = 1
        public var filesystemPolicy: FilesystemPolicy
        public var networkPolicies: [NetworkPolicy]
        public var process: ProcessPolicy
        public var landlock: LandlockConfig

        public init(
            name: String,
            filesystemPolicy: FilesystemPolicy = .default,
            networkPolicies: [NetworkPolicy] = [],
            process: ProcessPolicy = .default,
            landlock: LandlockConfig = .default
        ) {
            self.name = name
            self.filesystemPolicy = filesystemPolicy
            self.networkPolicies = networkPolicies
            self.process = process
            self.landlock = landlock
        }
    }

    public struct FilesystemPolicy: Sendable {
        public var includeWorkdir: Bool
        public var readOnly: [String]
        public var readWrite: [String]
        public var blocked: [String]

        public static let `default` = FilesystemPolicy(
            includeWorkdir: true,
            readOnly: ["/usr", "/lib", "/etc", "/proc", "/dev/urandom"],
            readWrite: ["/tmp"],
            blocked: []
        )

        public init(includeWorkdir: Bool, readOnly: [String], readWrite: [String], blocked: [String] = []) {
            self.includeWorkdir = includeWorkdir
            self.readOnly = readOnly
            self.readWrite = readWrite
            self.blocked = blocked
        }
    }

    public struct NetworkPolicy: Sendable {
        public var name: String
        public var endpoints: [NetworkEndpoint]
        public var binaries: [String]

        public init(name: String, endpoints: [NetworkEndpoint], binaries: [String] = []) {
            self.name = name
            self.endpoints = endpoints
            self.binaries = binaries
        }
    }

    public struct NetworkEndpoint: Sendable {
        public var host: String
        public var port: Int
        public var `protocol`: String
        public var enforcement: String
        public var access: String

        public init(host: String, port: Int = 443, protocol: String = "rest", enforcement: String = "enforce", access: String = "full") {
            self.host = host
            self.port = port
            self.protocol = `protocol`
            self.enforcement = enforcement
            self.access = access
        }
    }

    public struct ProcessPolicy: Sendable {
        public var runAsUser: String
        public var runAsGroup: String
        public var maxRuntimeSeconds: Int?
        public var denySpawn: [String]

        public static let `default` = ProcessPolicy(
            runAsUser: "sandbox",
            runAsGroup: "sandbox",
            maxRuntimeSeconds: 600,
            denySpawn: []
        )

        public init(runAsUser: String = "sandbox", runAsGroup: String = "sandbox", maxRuntimeSeconds: Int? = 600, denySpawn: [String] = []) {
            self.runAsUser = runAsUser
            self.runAsGroup = runAsGroup
            self.maxRuntimeSeconds = maxRuntimeSeconds
            self.denySpawn = denySpawn
        }
    }

    public struct LandlockConfig: Sendable {
        public var compatibility: String

        public static let `default` = LandlockConfig(compatibility: "best_effort")

        public init(compatibility: String = "best_effort") {
            self.compatibility = compatibility
        }
    }

    // MARK: - YAML Generation

    /// Generate YAML string from a Policy
    public func generateYAML(from policy: Policy) -> String {
        var yaml = "# OpenShell Policy: \(policy.name)\n"
        yaml += "# Generated by SwiftOpenShell SDK\n"
        yaml += "version: \(policy.version)\n"

        // Filesystem
        yaml += "filesystem_policy:\n"
        yaml += "  include_workdir: \(policy.filesystemPolicy.includeWorkdir)\n"
        if !policy.filesystemPolicy.readOnly.isEmpty {
            yaml += "  read_only:\n"
            for path in policy.filesystemPolicy.readOnly {
                yaml += "    - \(path)\n"
            }
        }
        if !policy.filesystemPolicy.readWrite.isEmpty {
            yaml += "  read_write:\n"
            for path in policy.filesystemPolicy.readWrite {
                yaml += "    - \(path)\n"
            }
        }
        if !policy.filesystemPolicy.blocked.isEmpty {
            yaml += "  blocked:\n"
            for path in policy.filesystemPolicy.blocked {
                yaml += "    - \(path)\n"
            }
        }

        // Network
        if !policy.networkPolicies.isEmpty {
            yaml += "network_policies:\n"
            for np in policy.networkPolicies {
                yaml += "  \(np.name):\n"
                yaml += "    name: \(np.name)\n"
                yaml += "    endpoints:\n"
                for ep in np.endpoints {
                    yaml += "      - host: \(ep.host)\n"
                    yaml += "        port: \(ep.port)\n"
                    yaml += "        protocol: \(ep.protocol)\n"
                    yaml += "        enforcement: \(ep.enforcement)\n"
                    yaml += "        access: \(ep.access)\n"
                }
                if !np.binaries.isEmpty {
                    yaml += "    binaries:\n"
                    for bin in np.binaries {
                        yaml += "      - path: \(bin)\n"
                    }
                }
            }
        }

        // Process
        yaml += "process:\n"
        yaml += "  run_as_user: \(policy.process.runAsUser)\n"
        yaml += "  run_as_group: \(policy.process.runAsGroup)\n"
        if let maxRuntime = policy.process.maxRuntimeSeconds {
            yaml += "  max_runtime_seconds: \(maxRuntime)\n"
        }
        if !policy.process.denySpawn.isEmpty {
            yaml += "  deny_spawn:\n"
            for cmd in policy.process.denySpawn {
                yaml += "    - \(cmd)\n"
            }
        }

        // Landlock
        yaml += "landlock:\n"
        yaml += "  compatibility: \(policy.landlock.compatibility)\n"

        return yaml
    }

    /// Save a policy to disk and return the file path
    public func save(policy: Policy) throws -> URL {
        let yaml = generateYAML(from: policy)
        let filename = policy.name
            .lowercased()
            .replacingOccurrences(of: " ", with: "-")
            .appending(".yaml")
        let url = policyDirectory.appendingPathComponent(filename)
        try yaml.write(to: url, atomically: true, encoding: .utf8)
        return url
    }

    /// List all saved policies
    public func listSavedPolicies() -> [URL] {
        let fm = FileManager.default
        guard let files = try? fm.contentsOfDirectory(at: policyDirectory, includingPropertiesForKeys: nil) else {
            return []
        }
        return files.filter { $0.pathExtension == "yaml" || $0.pathExtension == "yml" }
    }

    /// Delete a saved policy
    public func deletePolicy(named name: String) throws {
        let filename = name.lowercased().replacingOccurrences(of: " ", with: "-").appending(".yaml")
        let url = policyDirectory.appendingPathComponent(filename)
        try FileManager.default.removeItem(at: url)
    }

    // MARK: - Templates

    /// Built-in policy templates
    public enum Template: String, CaseIterable, Sendable {
        case developer = "Developer Agent"
        case content = "Content Agent"
        case research = "Research Agent"
        case privateAirGapped = "Private Agent"
        case dataAnalyst = "Data Analyst"
    }

    /// Get a policy from a built-in template
    public func template(_ template: Template, workspaceRoot: String? = nil) -> Policy {
        switch template {
        case .developer:
            return developerTemplate(workspaceRoot: workspaceRoot)
        case .content:
            return contentTemplate(workspaceRoot: workspaceRoot)
        case .research:
            return researchTemplate(workspaceRoot: workspaceRoot)
        case .privateAirGapped:
            return privateTemplate(workspaceRoot: workspaceRoot)
        case .dataAnalyst:
            return dataAnalystTemplate(workspaceRoot: workspaceRoot)
        }
    }

    private func developerTemplate(workspaceRoot: String?) -> Policy {
        var readWrite = ["/tmp"]
        if let ws = workspaceRoot { readWrite.append(ws) }

        return Policy(
            name: "developer-agent",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: ["/usr", "/lib", "/etc", "/proc", "/dev/urandom"],
                readWrite: readWrite,
                blocked: ["~/.ssh", "~/Library/Keychains", "~/.gnupg"]
            ),
            networkPolicies: [
                NetworkPolicy(name: "llm-apis", endpoints: [
                    NetworkEndpoint(host: "api.anthropic.com"),
                    NetworkEndpoint(host: "api.openai.com"),
                    NetworkEndpoint(host: "generativelanguage.googleapis.com"),
                ], binaries: ["/usr/local/bin/claude", "/usr/local/bin/codex"]),
                NetworkPolicy(name: "github", endpoints: [
                    NetworkEndpoint(host: "*.github.com", access: "read-write"),
                    NetworkEndpoint(host: "*.githubusercontent.com", access: "read-only"),
                ], binaries: ["/usr/bin/git", "/usr/local/bin/gh"]),
                NetworkPolicy(name: "package-registries", endpoints: [
                    NetworkEndpoint(host: "registry.npmjs.org"),
                    NetworkEndpoint(host: "pypi.org"),
                    NetworkEndpoint(host: "files.pythonhosted.org"),
                ])
            ],
            process: ProcessPolicy(maxRuntimeSeconds: 1800)
        )
    }

    private func contentTemplate(workspaceRoot: String?) -> Policy {
        var readWrite = ["/tmp", "~/Downloads"]
        if let ws = workspaceRoot { readWrite.append(ws) }

        return Policy(
            name: "content-agent",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: ["/usr", "/lib", "/etc"],
                readWrite: readWrite,
                blocked: ["~/.ssh", "~/Library/Keychains"]
            ),
            networkPolicies: [
                NetworkPolicy(name: "llm-apis", endpoints: [
                    NetworkEndpoint(host: "api.anthropic.com"),
                    NetworkEndpoint(host: "api.openai.com"),
                ]),
                NetworkPolicy(name: "social-apis", endpoints: [
                    NetworkEndpoint(host: "api.twitter.com"),
                    NetworkEndpoint(host: "graph.facebook.com"),
                    NetworkEndpoint(host: "www.googleapis.com"),
                ])
            ],
            process: ProcessPolicy(maxRuntimeSeconds: 600)
        )
    }

    private func researchTemplate(workspaceRoot: String?) -> Policy {
        var readOnly = ["/usr", "/lib", "/etc"]
        if let ws = workspaceRoot { readOnly.append(ws) }

        return Policy(
            name: "research-agent",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: readOnly,
                readWrite: ["/tmp"],
                blocked: ["~/.ssh", "~/Library/Keychains", "~/.gnupg"]
            ),
            networkPolicies: [
                NetworkPolicy(name: "llm-apis", endpoints: [
                    NetworkEndpoint(host: "api.anthropic.com"),
                    NetworkEndpoint(host: "api.openai.com"),
                ]),
                NetworkPolicy(name: "web-search", endpoints: [
                    NetworkEndpoint(host: "*.google.com"),
                    NetworkEndpoint(host: "api.perplexity.ai"),
                    NetworkEndpoint(host: "api.bing.microsoft.com"),
                ])
            ],
            process: ProcessPolicy(maxRuntimeSeconds: 600)
        )
    }

    private func privateTemplate(workspaceRoot: String?) -> Policy {
        var readWrite = ["/tmp"]
        if let ws = workspaceRoot { readWrite.append(ws) }

        return Policy(
            name: "private-agent",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: ["/usr", "/lib", "/etc"],
                readWrite: readWrite,
                blocked: ["~/.ssh", "~/Library/Keychains", "~/.gnupg", "~/.config"]
            ),
            networkPolicies: [], // Air-gapped: no network access
            process: ProcessPolicy(maxRuntimeSeconds: 300)
        )
    }

    private func dataAnalystTemplate(workspaceRoot: String?) -> Policy {
        var readWrite = ["/tmp"]
        if let ws = workspaceRoot { readWrite.append(ws) }

        return Policy(
            name: "data-analyst",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: ["/usr", "/lib", "/etc"],
                readWrite: readWrite,
                blocked: ["~/.ssh", "~/Library/Keychains"]
            ),
            networkPolicies: [
                NetworkPolicy(name: "llm-apis", endpoints: [
                    NetworkEndpoint(host: "api.anthropic.com"),
                    NetworkEndpoint(host: "api.openai.com"),
                ])
            ],
            process: ProcessPolicy(maxRuntimeSeconds: 1200)
        )
    }

    // MARK: - Migration from CommandPolicy

    /// Generate an OpenShell policy from existing CommandPolicy-style rules
    public func migrateFromCommandPolicy(
        workspaceRoot: String,
        readOnlyMode: Bool,
        blockedCommands: [String],
        allowedDomains: [String]
    ) -> Policy {
        var readWrite: [String] = ["/tmp"]
        var readOnly: [String] = ["/usr", "/lib", "/etc", "/proc", "/dev/urandom"]

        if readOnlyMode {
            readOnly.append(workspaceRoot)
        } else {
            readWrite.append(workspaceRoot)
        }

        let networkEndpoints = allowedDomains.map {
            NetworkEndpoint(host: $0)
        }

        return Policy(
            name: "migrated-policy",
            filesystemPolicy: FilesystemPolicy(
                includeWorkdir: true,
                readOnly: readOnly,
                readWrite: readWrite,
                blocked: ["~/.ssh", "~/Library/Keychains", "~/.gnupg"]
            ),
            networkPolicies: networkEndpoints.isEmpty ? [] : [
                NetworkPolicy(name: "allowed-endpoints", endpoints: networkEndpoints)
            ],
            process: ProcessPolicy(
                maxRuntimeSeconds: 600,
                denySpawn: blockedCommands
            )
        )
    }
}
